### ISSUE TITLE
XML Web Services 4, approved final release checklist

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/jax-ws-api#189]
Congratulations on the release approval of XML Web Services 4.0. My thanks to the team for attending to all these details. Here is a checklist to help you finalize this specification release. 

Please review the following:
- [x] promote api staging release, promote the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
- [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
- [x] if XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from Draft to Final.
- [x] approve the compatibility request.
- [x] the compatible implementation project/vendor MUST send an email to [tck@eclipse.org](mailto:tck@eclipse.org) for approval of the compatible implementation for trademark usage.
- [x]  merge any final release branch as appropriate for the branch management for the project.
- [x] Confirm that the project has updated the Jakarta EE API jar by submitting a PR to the jakartaee-api project that updates the version number of your API jar file.

**Comment by lukasj** [comment]
done
